#!/usr/bin/env python3
"""Build navigation indexes for the restructured Synapta repo.

Generates:
  /home/learner/Desktop/mewtwo/PROJECT_OVERVIEW.md
  /home/learner/Desktop/mewtwo/docs/RESULTS_INDEX.md
  /home/learner/Desktop/mewtwo/docs/ADAPTERS_INDEX.md
  /home/learner/Desktop/mewtwo/docs/DOCS_INDEX.md
"""
import json, os, sys
from pathlib import Path
from collections import defaultdict

ROOT = Path("/home/learner/Desktop/mewtwo")
DOCS = ROOT / "docs"
DOCS.mkdir(exist_ok=True)


def file_size_human(p):
    try:
        sz = os.path.getsize(p)
        for u in ['B', 'K', 'M', 'G']:
            if sz < 1024:
                return f"{sz:.0f}{u}"
            sz /= 1024
        return f"{sz:.1f}T"
    except OSError:
        return "?"


def safe_read_json(p, max_size=200_000):
    try:
        if os.path.getsize(p) > max_size:
            return None
        with open(p) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


# ============================================================
# RESULTS_INDEX.md
# ============================================================
def build_results_index():
    out = ["# Results Index — every JSON / artifact, with methodology and caveats\n"]
    out.append("Generated by `_restructure/build_indexes.py`. Reproducible.\n\n")
    out.append("**Scope:** all benchmark/eval result files produced by Synapta work.\n")
    out.append("Third-party benchmark fixtures (LLMs-Planning, tau-bench raw outputs) excluded.\n\n")

    # Section 1: Headline measurements (the ones that matter for the deck)
    out.append("---\n\n## 1. Headline measurements (deck-grade)\n\n")
    out.append("Numbers used in `SYNAPTA_PITCH_DECK.pptx` and findings.\n\n")

    out.append("### HumanEval n=164 — final corrected\n\n")
    out.append("| Mode | Pass@1 (v1 inline buggy) | Pass@1 (v2 rescored) | Files |\n")
    out.append("|---|---|---|---|\n")
    out.append("| Base Nemotron-30B | 22.0% | **56.1%** | `overnight_run/qa_pairs/humaneval_full_base{,_rescored}.jsonl` |\n")
    out.append("| Format Guard | 70.7% | **73.2%** | `overnight_run/qa_pairs/humaneval_full_format_guard{,_rescored}.jsonl` |\n")
    out.append("| **Delta** | +48.7 (inflated) | **+17.1** (defensible) | n=164, McNemar p<0.001 |\n\n")
    out.append("**Methodology note:** v1 used the original `extract_code` that dropped imports and stripped body indentation. v2 rescore applied corrected extraction to the SAME raw outputs (saved in JSONL `raw_output` field). See `findings/humaneval_n164.md` and `findings/humaneval_statistical_analysis.md`.\n\n")

    out.append("### Nemotron-30B Phase 1 single-adapter benchmarks\n\n")
    mr = safe_read_json(ROOT / "results/nemotron/master_results.json")
    if mr:
        out.append("| Config | ARC | HumanEval | MATH-500 | MBPP |\n")
        out.append("|---|---|---|---|---|\n")
        configs = ["baseline", "math", "code", "science", "merged"]
        for cfg in configs:
            arc = mr.get(f"{cfg}_arc_fixed", {}).get("score", "—")
            he = mr.get(f"{cfg}_humaneval_fixed", {}).get("score", "—")
            math = mr.get(f"{cfg}_math500", {}).get("score", "—")
            mbpp = mr.get(f"{cfg}_mbpp", {}).get("score", "—")
            def fmt(v): return f"{v:.1%}" if isinstance(v, (int, float)) else str(v)
            out.append(f"| {cfg} | {fmt(arc)} | {fmt(he)} | {fmt(math)} | {fmt(mbpp)} |\n")
        out.append("\n**File:** `results/nemotron/master_results.json` (n=100 ARC/HE/MBPP, n=200 MATH-500)\n")
        out.append("**Caveat:** HumanEval column likely under-counted by ~30 pp due to scoring bug (same as the n=25 deck claim). Use overnight_run/findings/humaneval_n164.md numbers for HumanEval.\n\n")

    out.append("### Token-Level Routing on Nemotron-30B\n\n")
    tr = safe_read_json(ROOT / "results/nemotron/token_routing_results.json")
    if tr:
        out.append(f"| Benchmark | Score | Correct | Total |\n|---|---|---|---|\n")
        for k, v in tr.items():
            score = v.get("score", "?") if isinstance(v, dict) else v
            correct = v.get("correct", "?") if isinstance(v, dict) else "?"
            total = v.get("total", "?") if isinstance(v, dict) else "?"
            out.append(f"| {k} | {score} | {correct} | {total} |\n")
        out.append("\n**File:** `results/nemotron/token_routing_results.json`\n\n")

    out.append("### Cold-swap latency profile\n\n")
    cs = safe_read_json(ROOT / "results/nemotron/cold_swap_metrics.json")
    if cs:
        out.append(f"- Total swaps: {cs.get('total_swaps')}\n")
        out.append(f"- Avg latency: {cs.get('average_latency_sec', 0)*1000:.1f} ms\n")
        out.append(f"- Max latency: {cs.get('max_latency_sec', 0)*1000:.1f} ms\n")
        out.append("\n**File:** `results/nemotron/cold_swap_metrics.json`\n\n")

    out.append("### Code Paradox replication (overnight)\n\n")
    cp = safe_read_json(ROOT / "overnight_run/qa_pairs/code_paradox_summary.json")
    cp_n200 = safe_read_json(ROOT / "overnight_run/qa_pairs/code_paradox_qwen_n200_summary.json")
    out.append("| Base model | Sample | Base | Math adapter | Code adapter | Δ (code−math) |\n")
    out.append("|---|---|---|---|---|---|\n")
    if cp:
        for model, r in cp.items():
            if 'error' in r: continue
            base = r['base']['acc']
            math = r['math_adapter']['acc']
            code = r['code_adapter']['acc']
            out.append(f"| {model} | n=50 | {base:.1%} | {math:.1%} | {code:.1%} | {(code-math)*100:+.1f} |\n")
    if cp_n200:
        base = cp_n200['base']['acc']
        math = cp_n200['math_adapter']['acc']
        code = cp_n200['code_adapter']['acc']
        out.append(f"| qwen_0.8b | **n=200** | {base:.1%} | {math:.1%} | {code:.1%} | **{(code-math)*100:+.1f}** ❌ |\n")
    out.append("| nemotron_3_nano_30b | n=200 | 41.5% | 50.5% | 56.0% | **+5.5** ✅ (original) |\n\n")
    out.append("**Files:** `overnight_run/qa_pairs/code_paradox_*.jsonl`\n")
    out.append("**Caveat:** n=50 cross-family results were small-sample flukes. Robust replication only at n=200 on Nemotron-30B. Full analysis in `overnight_run/findings/code_paradox_replication.md`.\n\n")

    # Section 2: Demo smoke tests
    out.append("---\n\n## 2. Demo smoke tests\n\n")
    out.append("Used to validate the demo server pipeline.\n\n")
    out.append("### Iter-2 smoke (max=256, baseline)\n")
    out.append("- 20 prompts × 4 modes = 80 generations\n")
    out.append("- Pass rates: base 95% / single_best 85% / token_routing 85% / format_guard 85%\n")
    out.append("- Files: `overnight_run/qa_pairs/demo_smoke_{base,single_best,token_routing,format_guard}.jsonl`\n\n")
    out.append("### Iter-9 polish smoke (max=512, post-fix)\n")
    out.append("- Same 20 prompts × 4 modes\n")
    out.append("- Pass rates: **all 4 modes at 95%** — adapter modes lifted with adequate token budget\n")
    out.append("- Files: `overnight_run/qa_pairs/demo_polish_*.jsonl`\n\n")

    # Section 3: All result files catalogued
    out.append("---\n\n## 3. Full result-file catalogue\n\n")
    with open('/home/learner/Desktop/mewtwo/_restructure/synapta_results_jsons.txt') as f:
        files = [l.strip() for l in f if l.strip()]
    by_dir = defaultdict(list)
    for fp in files:
        d = '/'.join(fp.split('/')[:-1])
        by_dir[d].append(fp.split('/')[-1])
    for d in sorted(by_dir):
        out.append(f"### `{d}/`\n\n")
        for f in sorted(by_dir[d]):
            full = ROOT / d.lstrip('./') / f
            sz = file_size_human(full)
            out.append(f"- `{f}` ({sz})\n")
        out.append("\n")

    out.append("\n---\n\n## 4. Caveats and known issues\n\n")
    out.append("- **HumanEval scoring bug** affected `results/nemotron/master_results.json` (Phase 1 single-adapter HumanEval column). Same bug in `overnight_run/qa_pairs/humaneval_full_*.jsonl` (v1) but corrected in `*_rescored.jsonl`. Use rescored numbers.\n")
    out.append("- **Code Paradox cross-family overclaim** rolled back. Original deck claimed replication across 3 base models; n=200 follow-up showed n=50 was a fluke. Only the +5.5 pp Nemotron-30B n=200 result is robust.\n")
    out.append("- **Demo bugs** in original `src/demo/server.py` (5 issues) caused 'crap answers' in early demos. Fix shipped May 2; backup at `src/demo/server_original_backup.py`. Smoke-test verification at 95% post-fix.\n")
    out.append("- **Results in `results/router_generation_*` and `results/md_section_generation_*`** are intermediate artifacts from router-training experiments, not final results. Treat as historical.\n")

    (DOCS / "RESULTS_INDEX.md").write_text("".join(out))
    print(f"Wrote RESULTS_INDEX.md ({sum(len(s) for s in out)} chars)")


# ============================================================
# ADAPTERS_INDEX.md
# ============================================================
def build_adapters_index():
    out = ["# Adapters Index — every PEFT adapter, with training methodology\n\n"]
    out.append("Generated by `_restructure/build_indexes.py`.\n\n")

    with open('/home/learner/Desktop/mewtwo/_restructure/all_adapters.txt') as f:
        configs = [l.strip() for l in f if l.strip()]

    # Group by base model
    by_base = defaultdict(list)
    for cfg_path in configs:
        full = ROOT / cfg_path.lstrip('./')
        cfg = safe_read_json(full)
        if not cfg:
            continue
        base = cfg.get('base_model_name_or_path', 'unknown')
        rank = cfg.get('r', '?')
        target = ','.join(cfg.get('target_modules', []))
        adapter_dir = full.parent
        rel = str(adapter_dir).replace(str(ROOT) + '/', '')
        # Adapter weight file
        wf = adapter_dir / 'adapter_model.safetensors'
        wf_size = file_size_human(wf) if wf.exists() else "—"
        by_base[base].append({
            'path': rel,
            'rank': rank,
            'target': target,
            'weight_size': wf_size,
        })

    out.append(f"**Total adapters:** {len(configs)} across {len(by_base)} base models.\n\n")

    out.append("---\n\n## By base model\n\n")
    for base in sorted(by_base):
        out.append(f"### `{base}`\n\n")
        adapters = by_base[base]
        out.append(f"({len(adapters)} adapters)\n\n")
        out.append("| Path | Rank | Target | Weight size |\n|---|---|---|---|\n")
        for a in sorted(adapters, key=lambda x: x['path']):
            out.append(f"| `{a['path']}` | {a['rank']} | {a['target']} | {a['weight_size']} |\n")
        out.append("\n")

    out.append("---\n\n## Canonical adapters used by inference / benchmarks\n\n")
    out.append("These are the adapters loaded by `src/demo/server.py`, `scripts/token_router_eval.py`, etc.\n\n")
    out.append("| Domain | Path | Notes |\n|---|---|---|\n")
    out.append("| Math | `checkpoints/nemotron_lori/adapters/math/best/` | Bit-identical to `hf_publish/math/` (hardlinked) |\n")
    out.append("| Code | `checkpoints/nemotron_lori/adapters/code/best/` | Bit-identical to `hf_publish/code/` (hardlinked) |\n")
    out.append("| Science | `checkpoints/nemotron_lori/adapters/science/best/` | Bit-identical to `hf_publish/science/` (hardlinked) |\n\n")

    out.append("---\n\n## Training intermediate checkpoints (preservation)\n\n")
    out.append("`checkpoints/nemotron_lori/adapters/{math,code,science}/checkpoint-N/` directories preserve\n")
    out.append("training history at every save step. Total ~3 GB across 3 domains. Not used by inference,\n")
    out.append("but kept for reproducibility — if a paper claim ever needs to be re-derived, the exact\n")
    out.append("checkpoint at every step is here.\n\n")
    out.append("If disk pressure ever forces cleanup, these are the safest deletion targets, in this order:\n")
    out.append("1. `checkpoint-N/` for N < final_step / 2 (early training, lowest reproducibility value)\n")
    out.append("2. `hidden_*/` checkpoints (emergency saves, mostly redundant)\n")
    out.append("3. `dare_sparsified/` (regeneratable from `final/` via `apply_dare_to_peft_model`)\n\n")

    (DOCS / "ADAPTERS_INDEX.md").write_text("".join(out))
    print(f"Wrote ADAPTERS_INDEX.md ({sum(len(s) for s in out)} chars)")


# ============================================================
# DOCS_INDEX.md
# ============================================================
def build_docs_index():
    out = ["# Docs Index — every Markdown file in the project\n\n"]
    out.append("Generated by `_restructure/build_indexes.py`.\n\n")

    with open('/home/learner/Desktop/mewtwo/_restructure/all_markdown.txt') as f:
        files = [l.strip() for l in f if l.strip()]
    files = [f for f in files if not f.startswith('./_restructure/_old_tmp_snapshot/')]

    out.append(f"**Total markdown files:** {len(files)}\n\n")

    # Group by directory
    by_dir = defaultdict(list)
    for fp in files:
        parts = fp.lstrip('./').split('/')
        d = '/'.join(parts[:-1]) if len(parts) > 1 else '(root)'
        by_dir[d].append(fp)

    # Section 1: Top-level + master docs (most important)
    important = ['(root)', 'docs', 'manuscripts', 'overnight_run', 'overnight_run/findings']
    out.append("## Master / canonical docs (read first)\n\n")
    for d in important:
        if d in by_dir:
            out.append(f"### `{d}/`\n\n")
            for fp in sorted(by_dir[d]):
                full = ROOT / fp.lstrip('./')
                sz = file_size_human(full)
                # Try to read first heading
                first_line = ''
                try:
                    with open(full) as f:
                        for line in f:
                            line = line.strip()
                            if line.startswith('#'):
                                first_line = line.lstrip('#').strip()
                                break
                            if line and not line.startswith('---'):
                                first_line = line[:80]
                                break
                except OSError:
                    pass
                name = fp.split('/')[-1]
                out.append(f"- **`{name}`** ({sz}) — {first_line}\n")
            out.append("\n")

    out.append("---\n\n## All other markdown files (organized by directory)\n\n")
    for d in sorted(by_dir):
        if d in important:
            continue
        out.append(f"### `{d}/`\n\n")
        out.append(f"({len(by_dir[d])} files)\n\n")
        for fp in sorted(by_dir[d]):
            name = fp.split('/')[-1]
            full = ROOT / fp.lstrip('./')
            sz = file_size_human(full)
            out.append(f"- `{name}` ({sz})\n")
        out.append("\n")

    (DOCS / "DOCS_INDEX.md").write_text("".join(out))
    print(f"Wrote DOCS_INDEX.md ({sum(len(s) for s in out)} chars)")


# ============================================================
# Top-level PROJECT_OVERVIEW.md
# ============================================================
def build_project_overview():
    out = ["# Synapta — Project Overview\n\n"]
    out.append("Generated 2026-05-02 by the restructure pass. Single source of truth for navigating this repo.\n\n")
    out.append("---\n\n")
    out.append("## What this project is\n\n")
    out.append("Adapter-routing platform for sovereign-AI enterprise deployment. Single base model + dozens of swappable domain experts, deployed inside customer firewall.\n\n")
    out.append("**Core finding:** Format Guard adapter routing on Nemotron-30B achieves **+17.1 pp HumanEval** over base (n=164, p<0.001).\n\n")
    out.append("---\n\n")
    out.append("## Headline numbers (defensible, deck-ready)\n\n")
    out.append("| Benchmark | Base Nemotron-30B | Our Routing | Lift | n |\n")
    out.append("|---|---|---|---|---|\n")
    out.append("| ARC-Challenge | 20.0% | 31.0% | +11.0 | 100 |\n")
    out.append("| MATH-500 | 41.5% | 56.0% | +14.5 | 200 |\n")
    out.append("| HumanEval (rescored v2) | **56.1%** | **73.2%** | **+17.1** | **164** |\n")
    out.append("| MBPP | 8.0% | 5.0% | -3.0 | 100 |\n\n")
    out.append("Code Paradox at n=200 on Nemotron-30B: code adapter (56%) > math adapter (50.5%) on MATH-500. **+5.5 pp**.\n\n")
    out.append("---\n\n")
    out.append("## Read in this order\n\n")
    out.append("1. **`overnight_run/FINAL_SUMMARY.md`** — what was done overnight 2026-05-02, with all wins/rollbacks\n")
    out.append("2. **`overnight_run/TALKING_POINTS.md`** — verbatim sentences for CTO meeting + YC application\n")
    out.append("3. **`overnight_run/DECK_UPDATE_GUIDE.md`** — exact find/replace edits for the deck\n")
    out.append("4. **`docs/RESULTS_INDEX.md`** — every results JSON catalogued\n")
    out.append("5. **`docs/ADAPTERS_INDEX.md`** — every PEFT adapter catalogued\n")
    out.append("6. **`docs/DOCS_INDEX.md`** — every markdown file catalogued\n")
    out.append("7. **`docs/MASTER_KNOWLEDGE_BASE.md`** — historical research chronicle (long, but comprehensive)\n\n")
    out.append("---\n\n")
    out.append("## Directory layout\n\n")
    out.append("```\n")
    out.append("mewtwo/\n")
    out.append("├── README.md                    # this file (or symlink to PROJECT_OVERVIEW.md)\n")
    out.append("├── PROJECT_OVERVIEW.md          # detailed structure map (this doc)\n")
    out.append("├── SYNAPTA_PITCH_DECK.{pptx,pdf}  # YC / CTO pitch deck\n")
    out.append("├── build_pitch_deck.py          # deck source\n")
    out.append("├── requirements.txt             # Python deps\n")
    out.append("├── setup_env.sh                 # env setup\n")
    out.append("│\n")
    out.append("├── docs/                        # master research + index docs\n")
    out.append("│   ├── MASTER_KNOWLEDGE_BASE.md\n")
    out.append("│   ├── MASTER_RESEARCH_CHRONICLES.md\n")
    out.append("│   ├── MASTER_EXPERIMENT_REPORTS.md\n")
    out.append("│   ├── MASTER_TASKS_AND_PLANS.md\n")
    out.append("│   ├── RESULTS_INDEX.md         # generated\n")
    out.append("│   ├── ADAPTERS_INDEX.md        # generated\n")
    out.append("│   └── DOCS_INDEX.md            # generated\n")
    out.append("│\n")
    out.append("├── manuscripts/                 # paper drafts\n")
    out.append("│   ├── synapta_systems.md\n")
    out.append("│   ├── code_paradox.md\n")
    out.append("│   └── compiled_manuscript.md\n")
    out.append("│\n")
    out.append("├── overnight_run/               # 2026-05-02 mission output (canonical recent state)\n")
    out.append("│   ├── FINAL_SUMMARY.md\n")
    out.append("│   ├── TALKING_POINTS.md\n")
    out.append("│   ├── DECK_UPDATE_GUIDE.md\n")
    out.append("│   ├── WAKE_UP_README.md\n")
    out.append("│   ├── findings/                # 7 detailed finding docs\n")
    out.append("│   ├── qa_pairs/                # 21 JSONL files of Q&A\n")
    out.append("│   ├── scripts/                 # reproducible runners\n")
    out.append("│   └── demo_artifacts/          # server_fixed.py — drop-in demo fix\n")
    out.append("│\n")
    out.append("├── models/                      # base model weights (60 GB)\n")
    out.append("│   ├── nemotron/                # Nemotron-H-30B (NemotronHForCausalLM)\n")
    out.append("│   └── Qwen3.5-0.8B/\n")
    out.append("│\n")
    out.append("├── checkpoints/                 # PEFT adapter training output\n")
    out.append("│   ├── nemotron_lori/adapters/{math,code,science}/\n")
    out.append("│   │   ├── best/                # canonical inference adapter\n")
    out.append("│   │   ├── final/               # last training step\n")
    out.append("│   │   ├── checkpoint-N/        # intermediate (training history)\n")
    out.append("│   │   └── dare_sparsified/     # post-hoc DARE sparsification\n")
    out.append("│   ├── lori_moe/                # LoRI-MoE Qwen-1.5B work\n")
    out.append("│   └── MATHEMATICS/             # ?\n")
    out.append("│\n")
    out.append("├── hf_publish/                  # publishing-ready adapters (hardlinked to checkpoints/...)\n")
    out.append("│   └── {math,code,science,merged}/\n")
    out.append("│\n")
    out.append("├── hf_kaggle_opensource/        # small-model adapter zoo + 3rd-party benchmarks\n")
    out.append("│   ├── outputs/                 # qwen_0.8b_*, nemotron_4b_* adapter checkpoints (matched ranks 1/2/8/128/1024/3072)\n")
    out.append("│   ├── benchmarks/              # tau-bench, LLMs-Planning (3rd-party suites)\n")
    out.append("│   └── results/                 # small-model eval outputs\n")
    out.append("│\n")
    out.append("├── router_adapters/             # router classifier checkpoints (Synapta v1 era)\n")
    out.append("├── submission_adapter/          # single packaged adapter (Synapta submission)\n")
    out.append("│\n")
    out.append("├── src/                         # Synapta source code\n")
    out.append("│   ├── demo/server.py           # FastAPI WebSocket demo (FIXED 2026-05-02)\n")
    out.append("│   ├── demo/server_original_backup.py  # pre-fix backup\n")
    out.append("│   ├── lori_moe/                # LoRI-MoE architecture (model, training, inference)\n")
    out.append("│   ├── adapters/, composition/, eval/, engine/, routers/, training/\n")
    out.append("│   └── ...\n")
    out.append("│\n")
    out.append("├── scripts/                     # standalone runners\n")
    out.append("│   ├── token_router_eval.py     # known-good Nemotron-30B routing benchmark\n")
    out.append("│   ├── master_pipeline.py       # Phase 1 single-adapter pipeline\n")
    out.append("│   ├── routing_grand_comparison.py  # 12-strategy bake-off\n")
    out.append("│   └── ...\n")
    out.append("│\n")
    out.append("├── results/                     # benchmark outputs\n")
    out.append("│   └── nemotron/                # Nemotron-30B benchmark JSONs\n")
    out.append("│\n")
    out.append("├── data/                        # datasets, prompts, traces\n")
    out.append("├── logs/                        # training and run logs\n")
    out.append("├── archive/                     # historical work (synapta_v1 etc)\n")
    out.append("├── backend/                     # backend services (Synapta v1 MLX)\n")
    out.append("├── kaggle_notebook/             # Kaggle deployment artifacts\n")
    out.append("├── paper_v2/                    # paper figures + tables\n")
    out.append("├── prompts/                     # prompt templates\n")
    out.append("├── tests/                       # unit tests\n")
    out.append("├── configs/                     # config files\n")
    out.append("│\n")
    out.append("├── _restructure/                # restructure audit logs (this pass)\n")
    out.append("├── .venv/                       # Python venv (do not touch)\n")
    out.append("├── perplexity-mcp-venv/         # MCP server venv\n")
    out.append("└── .git/                        # git history\n")
    out.append("```\n\n")
    out.append("---\n\n")
    out.append("## Reproducibility & safety\n\n")
    out.append("- Pre-restructure git tag: `pre-restructure-2026-05-02` at commit `e391284`\n")
    out.append("- Full pre-restructure backup at: `/home/learner/Desktop/mewtwo_PRE_RESTRUCTURE_BACKUP/`\n")
    out.append("- The restructure on 2026-05-02 only deleted regeneratable artifacts (`__pycache__`, `pip.pid`, `tmp/` snapshot) and replaced bit-identical duplicates with hardlinks. **No model weights or result JSONs were deleted.** All file paths still resolve.\n\n")
    out.append("---\n\n")
    out.append("## Known caveats (read before citing numbers)\n\n")
    out.append("1. **HumanEval scoring bug:** original `extract_code` in `scripts/master_pipeline.py` and `overnight_run/scripts/run_humaneval_n164.py` (v1) dropped imports from prompts and stripped body indentation. This caused systematic ~30 pp under-counting on Nemotron-30B HumanEval. **Use the v2 rescored numbers** in `overnight_run/qa_pairs/humaneval_full_*_rescored.jsonl` and findings in `overnight_run/findings/humaneval_n164.md`.\n\n")
    out.append("2. **Code Paradox cross-family overclaim retracted:** n=50 results on Qwen-0.8B and Nemotron-Mini-4B suggested cross-family replication, but n=200 follow-up on Qwen-0.8B showed the paradox does NOT replicate at full sample. **Robust claim:** +5.5 pp at n=200 on Nemotron-30B only. Honest update in `overnight_run/findings/code_paradox_replication.md`.\n\n")
    out.append("3. **Demo had 5 bugs** in original `src/demo/server.py` (repetition_penalty=1.3, wrong neural router input distribution, initial adapter not set, marketing system prompt, routing interval mismatch). Fixed 2026-05-02. Backup at `src/demo/server_original_backup.py`. Bug breakdown in `overnight_run/findings/demo_server_bugs.md`.\n\n")

    (ROOT / "PROJECT_OVERVIEW.md").write_text("".join(out))
    print(f"Wrote PROJECT_OVERVIEW.md ({sum(len(s) for s in out)} chars)")


if __name__ == "__main__":
    build_results_index()
    build_adapters_index()
    build_docs_index()
    build_project_overview()
    print("Done.")
